# Generated by Django 4.2.2 on 2023-06-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='budget',
        ),
    ]
