# Generated by Django 4.2.2 on 2023-06-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_budget_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='start_budget',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
