# Generated by Django 4.2.2 on 2023-06-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_start_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='start_budget',
            field=models.IntegerField(default=0),
        ),
    ]
